require('./integration/start')
require('./integration/test.000wallet.add')
require('./integration/test.001rule.decision.fetch')
require('./integration/test.weakPassword')
require('./integration/stop')
